apiVersion: v1
kind: Service
metadata:
  name: mi-tienda-service
spec:
  type: NodePort
  selector:
    app: mi-tienda
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080